### ISSUE TITLE
[Suggestion] Ender Item Conduit GUI Enhancements 

### ISSUE THREAD

**Issue by Petethelich** [SleepyTrousers/EnderZoo#101]
Ive been using the item conduits quite a bit lately there are a few things that are really getting on my nerves namely when changing the color channel. there should be a forward AND backwards like the mode/priority because if you go past it you have to cycle through all the colors again.

![Example of color channel:](http://i.imgur.com/NIsGry8.jpg)

in the existing item filter there should be an "add" button which checks the chest for any NEW items and ADDs them to the filter without removing the old items

![Example of ADD:](http://i.imgur.com/EeLgSEQ.jpg)

as well as remove duplicates in the filter because it really clutters up diamond chests 

![Example of clutter:](http://i.imgur.com/ntHpaNt.jpg)

Those are my only suggestions to an already incredible mod! I hope you find them useful :)

**Comment by MatthiasMann** [comment]
Well - EnderZoo has no item conduits.

But besides that - you can right click the buttons to toggle backwards. And the merge button is exactly what you are looking for in the existing item filter.

**Comment by Petethelich** [comment]
I should mention I am using an older version (the crack pack) and i realized I removed the arrow key for the insert/extract but TIL about right clicking!

Thank you
