### ISSUE TITLE
Client crash - java.lang.ClassCastException: crazypants.enderzoo.charge.EntityPrimedCharge cannot be cast to net.minecraft.entity.EntityLivingBase

### ISSUE THREAD

**Issue by ProsperCraft** [SleepyTrousers/EnderZoo#103]
http://pastebin.com/TxHv41a1

Disabling the mod serverside leads to these crashes in the client.

**Comment by tterrag1098** [comment]
Don't disable the mod serverside only. The client has different entity mappings. To do this serverside you should simply prevent the SPAWNING of the mobs you don't want.
