### ISSUE TITLE
Client crash - at net.minecraft.entity.ai.attributes.RangedAttribute.<init>(SourceFile:14)

### ISSUE THREAD

**Issue by ProsperCraft** [SleepyTrousers/EnderZoo#104]
http://pastebin.com/j8mEnLny

Changing the enabled/disabled mobs and having already had that mob in the world causes this client crash.

**Comment by HenryLoenwind** [comment]
There's nothing Ender Zoo can do here, unless we'd change it so that mobs cannot be disabled.

Problem is that Minecraft and Forge have no way of dealing with mobs that are in a saved game when there is no code for them (anymore). Forge can handle that for blocks and items, but not mobs.

**Comment by tterrag1098** [comment]
@ProsperCraft I'd advise you to re-enable the mobs, go ingame and disable the `doMobSpawning` gamerule, then a /cofh killall [mob name]. This should clear all the mobs and prevent them from spawning again so that you can disable them.

**Comment by tterrag1098** [comment]
Otherwise this is not a solvable issue, don't remove mobs from existing worlds.

**Comment by thegtz** [comment]
Wait how did you fix this? As I am getting this on a brand new world.

**Comment by tterrag1098** [comment]
Assure that the mob rules are the same between client and server.

**Comment by ProsperCraft** [comment]
We ended up removing the mod from the client and server at the time which
solved the crashes.

Now we don't edit the config on the server so the mobs match.
