### ISSUE TITLE
Dire Slime Spawning Suggestion

### ISSUE THREAD

**Issue by zzApotheosis** [SleepyTrousers/EnderZoo#109]
I think the Atomic Disassembler from Mekanism should count as a shovel/multitool and therefore prevent Dire Slimes from spawning.

**Comment by CrazyPants** [comment]
I think this has already been fixed. Are you using the latest version?

**Comment by zzApotheosis** [comment]
Yes, I have version 1.0.15.32. Dire Slimes have a chance of spawning when dirt is harvested with an Atomic Disassembler.

https://drive.google.com/file/d/0B_wljXPJi507T1FqOXo3LWthekE/view?usp=sharing
