### ISSUE TITLE
[Mod interaction] khndrel keght spawns from ender quarry + world hole upgrade

### ISSUE THREAD

**Issue by kotoroshinoto** [SleepyTrousers/EnderZoo#113]
absolutely massive numbers of these things spawn even when giving a silk touch upgrade to the quarry.

**Comment by tterrag1098** [comment]
This was fixed already, what version are you using?

**Comment by kotoroshinoto** [comment]
I'll have to check. Was it a recent fix?

**Comment by kotoroshinoto** [comment]
EnderZoo-1.7.10-1.0.14.31.jar

missed the newest version by a few days.

**Comment by tgstyle** [comment]
This also happens with a Mekanism Atomic Disassembler, latest version 1.0.15.32

**Comment by HenryLoenwind** [comment]
@tgstyle Then the Mekanism Atomic Disassembler pretends to be a real player. Nothing we can do from our side, that'd be on Mekanism's end.

**Comment by aidancbrady** [comment]
That is not the case, the Atomic Disassembler works just as a normal tool, passing the using player as the one breaking the block.

**Comment by HenryLoenwind** [comment]
So it is a hand tool? Not really related to this issue...

A khndrel keght is spawned when a dirt or grass block is broken by a player using a tool that is not effective on dirt. To determine if it is effective, we ask the tool. Only if the tool answers that it is not effective, will we potentially spawn one.

**Comment by ktole1999** [comment]
so anything other than a shovel will potentially spawn it. i get them all the time mining dirt by hand
