### ISSUE TITLE
ENDER ZOO NERFS VANILLA WHEAT GRAPHIC

### ISSUE THREAD

**Issue by chloeprince** [SleepyTrousers/EnderZoo#116]
When Ender Zoo is installed, Minecraft's Wheat Icon in NEI or the Hot Bar Slot, doesn't show up. The item is there, and you can see the stack size, but the item is invisible. This only happens with Ender Zoo, installed. When I remove it, its fine.

EnderZoo-1.7.10-1.0.15.32.jar
Forge .1448
MC 1.7.10

Error happens in Multi or Single Player

I also have a mod pack here:  http://www.mediafire.com/download/3ziehznhi63igxr/mods.zip
I have a Server here:  s34.hosthorde.com:25747

The server is white list - I can add you if you give me your Minecraft name.
You are welcome to download the pack and try it, and see the error for yourself.

**Comment by chloeprince** [comment]
WHEN LARGE SPIRE SPLITS IN TO AND MULTIPLIES IN TO A BUNCH OF SMALLER SPIDERS, IT CAUSES CLIENT CRASH AND LOCKS MY SERVER UP. NO REPOT GIVEN THOU... ANYONE ELSE HAVING THIS ISSUE TOO?

**Comment by CrazyPants** [comment]
I have stopped updating the 1.7.10 version now. 
EnderZoo doesnt add any spiders. They sound like the spiders added by Natura if you are using that.
