### ISSUE TITLE
Crash on v1.8.9 Server

### ISSUE THREAD

**Issue by kwpugh** [SleepyTrousers/EnderZoo#118]
Crashes on server start.

Crash report:  http://pastebin.com/raw/V4E3zHNw

**Comment by CrazyPants** [comment]
It is the WAILA integration failing. I will fix it asap.
Thanks for the report.

**Comment by CrazyPants** [comment]
Just uploaded a new version fixing the issue.

**Comment by kwpugh** [comment]
Great, thank you.   I'll loaded up on the server.
