### ISSUE TITLE
[Bug?] The Dirt slimes (Khndrel Keght) 1.8.9

### ISSUE THREAD

**Issue by Bellwar** [SleepyTrousers/EnderZoo#119]
I play on 1.8.9 i know it might not be full done but there is bug with it that it spawns even after breaking with shovel. (I have feels its higher with better shovel you dig it) And with Thaumcraft shovel i get up to 4 slimes from 3x3 hole thats so much.

**Comment by CrazyPants** [comment]
Thanks for the report.
It seems the logic has been reversed somehow during the port, so they only spawn when you are using a shovel. Will be fixed soon.

**Comment by CrazyPants** [comment]
New version fixing this issue is now available on curse
