### ISSUE TITLE
Concussion Creeper explosion near bedrock is bad!

### ISSUE THREAD

**Issue by firebrim** [SleepyTrousers/EnderZoo#122]
Please make sure  the Concussion Creepers can't teleport the player below bedrock level.

**Comment by b0bst3r** [comment]
What version of Ender Zoo is this?

**Comment by HenryLoenwind** [comment]
a very outdated one, I'd guess. That bug was fixed ages ago. Jul 20, 2015 to be exact.

**Comment by b0bst3r** [comment]
Yeah that's the reason I asked, I thought it was fixed in 1974 :D

**Comment by firebrim** [comment]
Im using EnderZoo-1.8.9-1.1.2

**Comment by HenryLoenwind** [comment]
so it seems to be a regression.

CrazyPants?
