### ISSUE TITLE
Haunted SAG Mill

### ISSUE THREAD

**Issue by NewEpochGaming** [SleepyTrousers/EnderZoo#129]
![Uploading 2016-03-28_20.30.02.png…]()
Hello,

My SAG Mill is haunted.
http://www.negaming.org/forum/m/30382475/viewthread/26669538-writing-on-my-macine/page/1

**Comment by b0bst3r** [comment]
You need ghostbusters not EIO devs.

**Comment by NewEpochGaming** [comment]
![2016-03-28_20 30 02](https://cloud.githubusercontent.com/assets/18130557/14095392/78bd6756-f525-11e5-9c11-c5bae0ea8bd3.png)

**Comment by MatthiasMann** [comment]
First of all - this is the issue tracker for EnderZoo - and the SAG Mill is part of EnderIO.
