### ISSUE TITLE
Primed Concussion TNT renders as owl.

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [SleepyTrousers/EnderZoo#131]
See title. I noticed this on server only, but not 100% sure if client is unaffected.

**Comment by MatthiasMann** [comment]
Verify that client & server config match 100%

**Comment by TheOnlySilverClaw** [comment]
I can confirm that IDs for owl and primed charge are 689998 in both.
I looked into your code and found that it is set that way by default.

**Comment by CrazyPants** [comment]
Oops. I will fix it shortly

**Comment by tterrag1098** [comment]
We shouldn't even be using global IDs

**Comment by CrazyPants** [comment]
Fixed.
