### ISSUE TITLE
Reinforced Obsidian + Thaumometer = Crash

### ISSUE THREAD

**Issue by ThePixelbrain** [SleepyTrousers/EnderZoo#132]
If you try to scan (or just even look at) a Reinforced Obsidian block with a Thaumometer you're Minecaft will crash. I tested it with EnderIO Version 2.0.32 and Thaumcraft Version 4.2.3.5 and the Infinity Evolved Skyblock Modpack.

[http://pastebin.com/3B3iEpmP](url)

PS: I'm new here, is there a better way of putting the crash log than posting the pastebin link?

**Comment by MatthiasMann** [comment]
This has nothing to do with EnderZoo.

**Comment by tterrag1098** [comment]
This has been fixed but I don't think it's been released.

**Comment by tterrag1098** [comment]
Valid issue, report it to EnderIO though
