### ISSUE TITLE
Server crashing from owls EnderZoo v1.9-1.2.38

### ISSUE THREAD

**Issue by BlueSilverXIII** [SleepyTrousers/EnderZoo#134]
Server keeps crashing with the owls activated. It works just fine in singleplayer or if owls are disabled.
thanks in advanced.

[crash-2016-05-20_01.28.08-server.txt](https://github.com/SleepyTrousers/EnderZoo/files/275726/crash-2016-05-20_01.28.08-server.txt)

**Comment by HenryLoenwind** [comment]
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_180640_a(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/AxisAlignedBB;
	at crazypants.enderzoo.entity.EntityUtil.canLandAtLocation(EntityUtil.java:200)

**Comment by BlueSilverXIII** [comment]
Awesome work as always. Thanks again
