### ISSUE TITLE
[1.10] FallenKnight entity crash - Ticking World

### ISSUE THREAD

**Issue by praetoras** [SleepyTrousers/EnderZoo#142]
http://pastebin.com/VDHAjtPQ

Crash details linked above. I've tried killing all entities in the world via server command, and the server runs fine until I log in, but as soon as the server attempts to load the fallen knight, the whole thing goes kaput. Unable to find out how to clear out the fallen knight that is causing the issue, or if the issue is the game attempting to spawn a fallen knight.

**Comment by HenryLoenwind** [comment]
You are using the EnderZoo version for Minecraft 1.9.4 on Minecraft 1.10 . That won't work.

**Comment by praetoras** [comment]
I appreciate the reply, thanks! I suspected that might be it, but wasn't sure, since I have a few 1.9.4 mods that run okay on it. I'll just keep an eye out for when the 1.10 comes and disable EnderZoo for now.
