### ISSUE TITLE
Blurry texture bug (all mobs except angry wither cat)

### ISSUE THREAD

**Issue by RichardEHarris** [SleepyTrousers/EnderZoo#155]
The textures appear blurry as if they've been upscaled badly in photoshop.
![image](https://cloud.githubusercontent.com/assets/19771641/19226460/1f456ee0-8ef3-11e6-849b-424d8f7be600.png)
![image](https://cloud.githubusercontent.com/assets/19771641/19226461/23b5248e-8ef3-11e6-9c91-d9d6ab7adc30.png)
![image](https://cloud.githubusercontent.com/assets/19771641/19226435/d50b68c0-8ef2-11e6-968c-b66a0c8166e2.png)
Here is the [fml-client-latest.log](https://www.dropbox.com/s/fdz20p6wynqskro/fml-client-latest.log?dl=0)

I'm using:
forge 12.18.2.2099
Ender Zoo 1.2.3.43

ModList:
Actually Additions
Akashic Tome
AppleCore
Auto Packager
AutoRegLib
Baubles
BD Lib
Better Builders Wand
Better Combat Mod
Better FPS
Biomes O Plenty
Blood Magic
Botania
Chameleon
Chisel
Chisel and Bits
Cooking for Blockheads
Cyclic
Deep Resonance
Drawers and bits
ElecCore
Ender Core
Ender IO
Ender Zoo
Enviromental Tech
Extra Utilities
Farseek API
Fast leaf decay
Flat Colored Blocks
Forestry
FTB Lib
FTB Utilities
Gendustry
Guide API
Immersive Engineering
Industrialcraft
Inventory Sorter
Ironchest
JEI
JEI Bees
Journeymap
Just Enough Resources
Light Level Overlay
Mantle
mcjtylib
MCMultiPart
Mod Name Tooltip
MorphOTool
Mouse Tweaks
Not Enough Wands
OpenComputers
Pams HarvestCraft
Platforms
Player Rugs
Progressive Automation
PSI
Quantum Flux
Quantum Storage
Quark
Random Things
Reborn Core
Redstone Paste
Refined Storage
RFTools
RFTools Dimensions
Roots
ShetiPhian Core
Simple Generators
Sound Filters
Storage Drawers
Streams
Super Crafting Frame
TechReborn
The One Probe
Tinkers Construct
Tinkers Tool Leveling
Tinkers' Addon
Tomb Many Graves
ValkyrieLib
Weapon Case Loot
Zoology

**Comment by Peach774** [comment]
I have this problem as well. It seems to break other mobs from other mods' textures too!
