### ISSUE TITLE
[1.10.2] Add Wither & Decay enchanted book recipies to the EnderIO enchanter

### ISSUE THREAD

**Issue by TechAsh** [SleepyTrousers/EnderZoo#159]
I assume there are no recipes for these books at the moment because if the recipes do exist they don't show up in JEI and I can't figure them out.

**Comment by MatthiasMann** [comment]
You can add them yourself by editing the recipes files (EnchanterRecipes_User.xml). Once you have found a recipes which you think has good balance you could post the relevant lines here.

**Comment by TechAsh** [comment]
Ok, perhaps you could give me a hint as to the name of the enchantments for the config file. I've tried the below config, and I've also tried "witherArrow" and "witherWeapon" (which seems to be what the enchantments are referred to in the code), but neither work. I get an error:

[EnderIO/EnderIO]: Could not find enchantment with name EnderZoo:withering when parsing enchanter recipes.

`
<enchantment name="EnderZoo:withering" costPerLevel="5" >
  <itemStack modID="minecraft" itemName="skull" itemMeta="1" />
</enchantment>
  
<enchantment name="EnderZoo:decay" costPerLevel="5" >
  <itemStack modID="EnderZoo" itemName="itemWitheringDust" />
</enchantment>
`

On a side note, do you know if it's possible to use a potion as the ingredient?

As for this being the wrong project, I had no way of knowing, I figured it would be EnderZoo that inserted the recipes into the Enchanter as this is the mod that adds the enchantments.

**Comment by HenryLoenwind** [comment]
yeah, this could go both ways. I'm actually surprised we don't already have those recipes.

About potions: I need to check the code, I know that our anvil recipes can work with potions but or sag mill recipes cannot.

The IDs I can find out, don't worry.
