### ISSUE TITLE
Server crash in minecraft 1.10.2 seems to be either ender io or biomes o plenty.

### ISSUE THREAD

**Issue by felixnigh7** [SleepyTrousers/EnderZoo#162]
Hello, sorry if this isn't the best place to post server errors. My server running version 1.50 of all the mods, and previously 1.42b, crashes almost every 10 minutes. I've updated the modpack, java, and my entire OS, but nothing seems to fix it. Does anyone have any ideas?

here's the crash report: http://pastebin.com/rAEFCX7c

here's the server log since I logged in: http://pastebin.com/BcDFzPTW

Thanks in advance. Really don't want to restart my world again but will if I have to.

**Comment by HenryLoenwind** [comment]
that's BoP https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.10.2-5.0.x/src/main/java/biomesoplenty/common/block/BlockBOPGrass.java#L218 --- it's calling the mathod on the block with the wrong state instead of calling it on the state directly.
