### ISSUE TITLE
EnderIO Crafter

### ISSUE THREAD

**Issue by jrwizzard** [SleepyTrousers/EnderZoo#164]
The 'LV Wire Coil'(immersive engineering) will not craft in the EnderIO Crafter.

**Comment by jrwizzard** [comment]
OOps.. I am playing skyfactory 3 as of 1/27/2017

**Comment by CanisUnbounded** [comment]
FYI: BluSunrize/ImmersiveEngineering#1873 (for refrence)

**Comment by MatthiasMann** [comment]
@jrwizzard This is EnderZoo not EnderIO

**Comment by jrwizzard** [comment]
The report bug link on the enderio webpage was sent to enderzoo. whatever.

**Comment by HenryLoenwind** [comment]
look again...
