### ISSUE TITLE
Server crashes infrequently, eventually crashes upon client connection. Disabling mods stops crash.

### ISSUE THREAD

**Issue by treaddy** [SleepyTrousers/EnderZoo#170]
Using the FTB Beyond pack. Server is stable after worldgen and client connection. Crashes infrequently, then the crashes become more frequent. Suspect EnderCore/IO and latent Tesla RF API errors. Eventually client connections crash the server instantly. Updating the mod, or Use/Non-use of items/machines don't  prevent the crash. Disabling the mod and core entirely seems to prevent server crashes. Log attached.
[crash-2017-03-14_20.41.06-server.txt](https://github.com/SleepyTrousers/EnderZoo/files/842964/crash-2017-03-14_20.41.06-server.txt)

**Comment by HenryLoenwind** [comment]
https://github.com/rwtema/extrautilities/issues/1342

Also, did you see this text in the crash? "(That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.)"

Also, this is the issue tracker for Ender**Zoo**.

**Comment by treaddy** [comment]
Thanks for info. Also I realised, issue closed 3 minutes before you replied. Cheers.
