### ISSUE TITLE
[1.12.2] Ticking Entity Crash with FallenKnight

### ISSUE THREAD

**Issue by Morpheus1101** [SleepyTrousers/EnderZoo#198]
crash @ https://gist.github.com/Morpheus1101/cec96210163a3e3c8d1d1be87af7f840 may also be related to #193

**Comment by HenryLoenwind** [comment]
Unrelated. This is a coremod producing invalid code.

**Comment by Morpheus1101** [comment]
I'll start removing coremods untill i no longer get this error

**Comment by Morpheus1101** [comment]
Not sure what was causing this as id stopped working  on the pack this was in and just started again.  Updated a lot of things as well as a forge and this no longer occurs.
