### ISSUE TITLE
Request - Please split conduits to a separate mod

### ISSUE THREAD

**Issue by IamStig** [SleepyTrousers/EnderZoo#201]
There are not many decent alternatives to the redstone signal handling or same space power, item, rs and liquid connecting, Having the conduits separate may make it easier to update them for a new MC version earlier.
Just an idea. Your efforts are appreciated. Thanks for maintaining this essential mod.

**Comment by tterrag1098** [comment]
Wrong repo and https://github.com/SleepyTrousers/EnderIO/tree/master/enderio-conduits

**Comment by IamStig** [comment]
Sorry I just followed the link from enderio.com to "Bug Reports and SUGGESTIONS" didn't think I miss clicked. ¯\_(ツ)_/¯ . I'll take a look at the link. Thanks tterrag

**Comment by HenryLoenwind** [comment]
you mean this one?

![image](https://user-images.githubusercontent.com/1485873/37516928-1d30eb12-2910-11e8-9c9a-26efd1f9c0c4.png)

**Comment by IamStig** [comment]
That's the one

**Comment by AnrDaemon** [comment]
And you did not see a difference between EnderIO and EnderZoo? >.<
