### ISSUE TITLE
Khndrel Keght config option?

### ISSUE THREAD

**Issue by KollinsPlays** [SleepyTrousers/EnderZoo#204]
Looking through EnderZoo.cfg and SpawnConfig_Core.xml I wasn't able to find a way to disable or change the spawn chance for the Khndrel Keght (the mob that randomly spawns when dirt is broken.) 
Please add a config option, or if it is already available, add comments or sample settings to disable or change the spawn chance for this mob.

**Comment by aileron565** [comment]
If I recall, it's called Dire Slime in the configs

**Comment by HenryLoenwind** [comment]
You can either set `direSlimeEnabled` to false or set their span chance to 0 (recommended).
