### ISSUE TITLE
WitherArrow Enchantment Off-Hand Interaction

### ISSUE THREAD

**Issue by znxster** [SleepyTrousers/EnderZoo#206]
I am using Ender Zoo v1.12.1-1.4.0.49 inside the FC3 modpack.

The Wither Arrow enchantment is missing a name as the enchant book "enchantment.witherArrow" inside JEI.

Anyway, when applied to a bow and placed in my off-hand, the wither effect will apply on my primary hand as well. This means I gain the power to wither punch! (or sword etc).

**Comment by HenryLoenwind** [comment]
The first one either is a JEI bug or no longer relevant for the next version.

The second on is a vanilla/forge bug. It applies the offhand item's enchantments on every hit in addition to the mainhand ones, expecting it to contain armor enchantments only.

**Comment by HenryLoenwind** [comment]
PS: You get the same effect with Bane of Arthropods...

-> https://bugs.mojang.com/browse/MC-131637

**Comment by tyler489** [comment]
Also fortune and looting :)

**Comment by HenryLoenwind** [comment]
tyler, that would be a different bug. The code path that applies bane (`Enchantment.onEntityDamaged()`) is not used for anything else in vanilla.

However, Thorns also shares this trait. Here any item in any hand triggers instead of just armor slots.

**Comment by znxster** [comment]
Many thanks for the quick feedback, seems likely we should close this issue as it isn't with the mod itself.
