### ISSUE TITLE
onPotionRegister doesn't check if floating potion is disabled

### ISSUE THREAD

**Issue by noobanidus** [SleepyTrousers/EnderZoo#213]
Instead, RegistryHandler.java:47 registers the return from getFloatingPotion without checking if config.floatingPotionEnabled. This causes a crash on startup as the resulting variable is null.

Accidentally disabled the potion as I was scrolling down to disable some of the other mobs.

**Comment by tyler489** [comment]
Are you using ender zoo or the new enderio zoo?

**Comment by noobanidus** [comment]
Specficially EnderZoo-1.12.1-1.4.0.49. Sorry, I didn't realise there was a new version! I didn't notice on the EnderZoo minecraftforge page that there was a new version and that this one wasn't being updated.
