### ISSUE TITLE
Crash my server

### ISSUE THREAD

**Issue by SeagalKru** [SleepyTrousers/EnderZoo#216]
[crash-2019-03-31_18.53.31-server.txt](https://github.com/SleepyTrousers/EnderZoo/files/3026806/crash-2019-03-31_18.53.31-server.txt)

**Comment by tyler489** [comment]
Enderzoo is no longer being updated. Please test with enderio zoo
Https://minecraft.curseforge.com/projects/ender-io-zoo

**Comment by HenryLoenwind** [comment]
The fallen knight es being attacked by an entity that doesn't have a location in the game. Not having one is invalid, report that to the mod that adds that entity, whatever it is.
