### ISSUE TITLE
My god, I've had at the end of this scold EnderZoo! This is the stupidest thing I ever did. I'm really sorry, very, very sorry...

### ISSUE THREAD

**Issue by wuligeshou** [SleepyTrousers/EnderZoo#222]

**Comment by CitiesXL2815** [comment]
We don't Care what you think about the mod, everyone else loves it, so don't come here and complain to us that mod sucks keep it to yourself and don't use it, this is for report bugs, crashes and Suggestion @wuligeshou

**Comment by wuligeshou** [comment]
末影动物园是侵权mod你知道吗？

EnderZoo is an infringing mod, do you know?

**Comment by wuligeshou** [comment]
> We don't Care what you think about the mod, everyone else loves it, so don't come here and complain to us that mod sucks keep it to yourself and don't use it, this is for report bugs, crashes and Suggestion @wuligeshou

EnderZoo is an infringing mod, do you know?

**Comment by wuligeshou** [comment]
EnderZoo is an infringing mod, do you know?

**Comment by CitiesXL2815** [comment]
Careful what you say we are tempted to report you to github for Rude Behavior, keep those words to yourself

**Comment by ferriarnus** [comment]
Infringing on what? All you seem to be doing is yelling that you don't like the mod. So don't use it. No one forces you, you don't need to play it. Just take another mod and let us be? But know that if you continue, you will get reported.
