### ISSUE TITLE
NPE on loading previous world with disabled Wither Cats

### ISSUE THREAD

**Issue by Macropyre** [SleepyTrousers/EnderZoo#34]
Had one too many run ins with Wither Witch + Cat combo, so I disabled the cats to ease up on my worries when exploring.

However, world crashes when I try to get in it now. Disabled cats in the .cfg file.

Recent version of EnderZoo, Forge 10.13.2.1230 .

**Comment by CrazyPants** [comment]
Stack trace is gone. If this is still an issue, please reraise with a new error.
