### ISSUE TITLE
Server crash - hit zombie horse with Cursed Spirits Blade of Thaumic Tinkering

### ISSUE THREAD

**Issue by Terpo** [SleepyTrousers/EnderZoo#44]
I ran around to kill some mobs with the Cursed Spirit's Blade of Thaumic Tinkering. After killing serval monsters the server crashed while attacking a zombie horse + knight. I did kill a few of them before the crash without problems.

http://pastebin.com/PW2RixTw

EnderZoo-1.7.10-1.0.7.16
Thaumcraft-1.7.10-4.2.2.0
ThaumicTinkerer-2.5-1.7.10-162

**Comment by CrazyPants** [comment]
I cant figure out how this could happen. has this just been a once off?

**Comment by Terpo** [comment]
I think this crash happend more than one time. But to be fair, maybe it is already fixed somehow. I will try to reproduce the crash after our next update next weekend. Hope thats ok for you :)
