### ISSUE TITLE
Enchantment issue with fallen knights.

### ISSUE THREAD

**Issue by Neodark7** [SleepyTrousers/EnderZoo#56]
Same issue as https://github.com/CrazyPants/EnderZoo/issues/42 with the latest versions of EIO and EZ

http://pastebin.com/W3nqZQH2

**Comment by doushio9967** [comment]
Most likely caused Forbidden Magic, unless you have some other mod that also messes up enchants like FM.
All of its enchants have a weight of 0, so if any of them show up as the only enchant in the Collection in getRandomItem when it's trying to add (more) enchants to the entity's held item you'll get that exception..

EnderZoo and Fallen Knights showing up in the stacktrace is a red herring.
FM's Wrath enchant risk you the same crash for entities spawning with a (possibly enchanted) axe, for example. Which is the exact problem I had to debug the other day.

Take this with a grain of salt, of course. In my case I was in eclipse's debugger with a breakpoint on that throw() so I could confirm for myself that it was really the FM enchants that was messing it up, and your problem could be totally unrelated.

**Comment by Cobra1117** [comment]
Also having this issue, although my stack trace is slightly different: http://pastebin.com/T1pmQRqM

**Comment by SpitefulFox** [comment]
Sure would've been nice to hear about this on my end instead of people complaining about crashes caused by my mod behind my back.
