### ISSUE TITLE
Server wither cat crash

### ISSUE THREAD

**Issue by AnonymousPuppy** [SleepyTrousers/EnderZoo#57]
I'm using a custom modpack, forge .1240, and EnderZoo-1.7.10-1.0.9.18.jar. A player on my server hit a wither cat, and the server crashed. It was a seemingly random occurrence, but I'd appreciate it if you could take a look, so it doesn't happen again.

Here is the crash report: http://pastebin.com/AFKJA8SL

Please take a look at this whenever you can, thank you :)

**Comment by zedle** [comment]
I'm getting this as well. Using direwolf20 1.0.3.. tried updating to the latest enderzoo to no avail.
