### ISSUE TITLE
Mob Enabling/Disabling Bug [1.0.9.18]

### ISSUE THREAD

**Issue by malignantMystic** [SleepyTrousers/EnderZoo#60]
On a Resonant Rise 3 server (version 3.2.2.1, if that helps), whenever we set one of your mobs to "false" in enderzoo.cfg, it occasionally crashes players and the log mentions the mobs even though they can't actually exist. Not sure what causes this, but below is a link to a sample crash one of our players has provided.

http://pastebin.com/Z7AvXBMx

**Comment by Yorkforce** [comment]
Would like to confirm this issue too, it appeared to be a guardian causing the problem, server was on hard difficulty.

Disabling the mod completely solved the problem.

**Comment by flagoss** [comment]
I have the same error. I disabled Wither Cats in the server config. After couple of min, 2 players crashed and were always crashing again while loggin in. They had to disable the Wither Cat in there local config and then they were able to join the server without crashing.

**Comment by xenoflot** [comment]
I experienced the same problem as flagoss's users. Until I also updated the client's config file to have withercats disabled, I would crash on logging in.  My logs here http://pastebin.com/U8LD0fHg

**Comment by CrazyPants** [comment]
Client and server configs must be in sync. Not much I can do about this.

**Comment by jawdylawdy** [comment]
That's patently untrue. Entities always need to be valid on both client and server side, even if they're not allowed to spawn in a single-player world.

**Comment by HenryLoenwind** [comment]
It may be a good idea to split the "enabled" config value into "enabled" and "spawn". That way map makers can disable the natural spawning but still place spawners into the world.

And it'd take care of this problem.
