### ISSUE TITLE
cant change spawn config

### ISSUE THREAD

**Issue by dmtryzhkv** [SleepyTrousers/EnderZoo#64]
hey guys. i want to change wither witches spawn rate. its 5 and i want to make it 20, but when i do it, in core xml, it automaticly changes itself to 5 again. is there a way to prevent that?

**Comment by CrazyPants** [comment]
You need to make the changes in the user XML file

**Comment by dmtryzhkv** [comment]
can you lead me what change should i do in that file?

**Comment by CrazyPants** [comment]
<entry id="WitherWitch" mobName="enderzoo.WitherWitch" rate="5" remove="true">
    <biomeFilter type="any">
      <biome type="FOREST" />
      <biome type="SWAMP" />
      <biome type="PLAINS" />
      <biome type="HILLS" />
      <biome type="MOUNTAIN" />
      <biome type="NETHER" exclude="true" />
      <biome type="END" exclude="true" />
    </biomeFilter>
    <dimensionExclude name="Twilight Forest"/>
  </entry>

   <entry id="WitherWitch" mobName="enderzoo.WitherWitch" rate="20" minGroupSize="1" maxGroupSize="1">
    <biomeFilter type="any">
      <biome type="FOREST" />
      <biome type="SWAMP" />
      <biome type="PLAINS" />
      <biome type="HILLS" />
      <biome type="MOUNTAIN" />
      <biome type="NETHER" exclude="true" />
      <biome type="END" exclude="true" />
    </biomeFilter>
    <dimensionExclude name="Twilight Forest"/>
  </entry>

**Comment by CrazyPants** [comment]
I will update the user file with some examples
