### ISSUE TITLE
AlloySmelterRecipes_Core.xml

### ISSUE THREAD

**Issue by demethan** [SleepyTrousers/EnderZoo#66]
Hi, 

I'm trying to change the bronze recipe to 3 copper and 1 thin for the Alloy Smelter. After a startup of the pack, the recipe is put back to 3 tin and 1 copper. 

Is there a way to prevent that?

Thanks.

**Comment by tterrag1098** [comment]
You have to edit the user file, not core. The comments in the files are
very clear.

**Comment by demethan** [comment]
I tried that too.  I can't override the recipe to match all the other mods.

**Comment by CrazyPants** [comment]
This has been posted against the wrong mod. Could you please report to this here: https://github.com/SleepyTrousers/EnderIO/issues
