### ISSUE TITLE
Concusion Creepers can Teleport you past bedrock

### ISSUE THREAD

**Issue by Dracohuman** [SleepyTrousers/EnderZoo#69]
This my be a uniqe instances in wich thaumcraft is involve but since concustion creepers can spawn in tainted lands. they also spawn in the thaumcraft dimentional doungion. alows them to teleport you outside of the world boundry to fall to your doom im not sure but this may also point out that it has the potential to teleport you into the void elsewhere not just these doungeons.

**Comment by tterrag1098** [comment]
If there is an issue past normal <0 bedrock, you should probably blacklist the concussion creeper from that dimension.
