### ISSUE TITLE
Wither Cat Spawning Weirdness

### ISSUE THREAD

**Issue by Thiana** [SleepyTrousers/EnderZoo#70]
I recently built a void mob farm and for some strange reason there are Wither Cats appearing on the roof even though it's fully lit. They dont appear to spawn in high light levels elsewhere so I'm assuming its some sort of interaction with the Draconic Evolution mob grinder? I've tried raising the roof but they're still appearing even when they are 12 blocks above the killing floor. Or perhaps the Wither Witches are spawning them as they fall into the grinder?

The longer I leave them, the more of them appear up there. /cofh killall eventually becomes a requirement.

If you dont know whats causing it, could you please add the ability to despawn a cat without a witch after a certain amount of time (5 min?) so that they dont accumulate to insane levels. Thanks.

Pack: FTB Infinity (with a few additions and subtractions, nothing related to mob spawns though)
EnderZoo: 1.0.9.18
Draconic Evolution: 1.0.1.snapshot5

![2015-03-14_07 12 13](https://cloud.githubusercontent.com/assets/405832/6651479/40aff2c0-ca1a-11e4-8fba-4ed08bb9346c.png)

**Comment by CrazyPants** [comment]
This would be caused by the cats being spawned in when the witch is. I will have a think about how to deal with this.

**Comment by Kazzamkablam** [comment]
I noticed that wither cats have tendency of glitching through solid blocks when spawning in my spawner room, likely related.

**Comment by Seegras** [comment]
They spawn on the dark glass of my mob farm, and they even spawn on the bedrock below my mob farm. You should really check when spawning whether a location is suitable.
