### ISSUE TITLE
Dire Wolves spawn in well-lit bases

### ISSUE THREAD

**Issue by rivveste** [SleepyTrousers/EnderZoo#72]
Dire Wolves appear to be hard-coded to spawn in any light level- https://github.com/SleepyTrousers/EnderZoo/blob/57ca3cfdbc8b2cc760554a45074b4ed90bf5019f/src/main/java/crazypants/enderzoo/entity/EntityDireWolf.java#L75. Found this via the Regrowth modpack, where the default biomes are changed, and dire wolves spawn all over well-lit bases.

**Comment by EchoingZen** [comment]
Regrowth modpack as well.  Dire wolves should certainly be changed to obey typical spawn light levels.
