### ISSUE TITLE
Disable wither cats, client crash

### ISSUE THREAD

**Issue by Beefuser12** [SleepyTrousers/EnderZoo#76]
Re-enabling them fixed the problem. 

Resonant Rise.

**Comment by jmurrayufo** [comment]
Can confirm under Direwolf20 v1.1.1, running ender zoo 1.0.9.18. Very annoying as they seem to bypass walls and glitch out spawning containment setups.

**Comment by CrazyPants** [comment]
Where the spawns disabled on both the client and server?
Needs to be done on both.
If this is not the issue I will need a crash log so I can investigate the problem.
