### ISSUE TITLE
dread potion effect from abyssalcraft mod conflicts with potion of decay

### ISSUE THREAD

**Issue by abidoang** [SleepyTrousers/EnderZoo#77]
I already downloaded the newest version that can resolve wither potion conflict from the config (it also happened to me with potion of leaping) and after I enabled it, the wither effect in potion of leaping is no longer there, but now potion of decay has both wither effect and dread potion effect from The Abyssalcraft mod (link: http://bit.ly/1AzrK0j).
<a href="http://imgur.com/5nE6uyp"><img src="http://i.imgur.com/5nE6uyp.jpg" title="source: imgur.com" /></a>
(the potion had different recipe from each mods, but it will produce the same potion)
When I tried to use the potion on myself, I got this crash: http://pastebin.com/1se3M7mL

**Comment by CrazyPants** [comment]
Changing 'useAltWitherPotionEffectMask' to true in the config should resolve this.
Can you please re-raise the issue if this doesnt reolve it?
