### ISSUE TITLE
Wither Cats (This is definitely not right...)

### ISSUE THREAD

**Issue by SniperHauss89** [SleepyTrousers/EnderZoo#78]
Hi, I discovered a strange "bug" I guess with the newest 1.7.10 build of ender zoo where the Wither Cats spawn with a rather strange graphical glitch. I plan to disable them for now but I thought I would put this here first. (NOTE: there like that with or without any other mods and naturally spawned or spawned in.)

![2015-04-02_15 04 00](https://cloud.githubusercontent.com/assets/9005067/6971394/38158672-d94a-11e4-8125-98673ef06f72.png)
![2015-04-02_15 04 04](https://cloud.githubusercontent.com/assets/9005067/6971393/3814c34a-d94a-11e4-9d03-c3dd30545401.png)
I don't think that's right...

**Comment by tterrag1098** [comment]
Uh what. @CrazyPants what did you do? O.o

**Comment by darkdata** [comment]
im having same issue with latest

**Comment by SirKastros** [comment]
here is what they look like for me
![2015-04-04_22 16 42](https://cloud.githubusercontent.com/assets/6454124/6995597/8f4cd56a-db18-11e4-8a82-d5f27306c592.png)

**Comment by ate0ate** [comment]
Sure does make them easy to see in the dark though!:P
![2015-04-05_19 27 14](https://cloud.githubusercontent.com/assets/5237757/7045763/eb228cfa-ddce-11e4-8c77-b078292afd6c.png)

**Comment by warezit** [comment]
lol @ate0ate ...
Confirmed:
![image](https://cloud.githubusercontent.com/assets/8278779/7081118/a1b48dae-df02-11e4-87e8-6c1abb8949d7.png)

**Comment by JoshuaDR** [comment]
Me too. Please fix it
![2015-04-11_11 56 42](https://cloud.githubusercontent.com/assets/11750955/7100180/eb2289f0-e042-11e4-944e-5da099c33bfb.png)

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderZoo/commit/658564e08d3b60ea685c9ffb6771c0fe45278b8d

Sorry it took me so long to get to this, I've been busy with other stuff. New release soon.
