### ISSUE TITLE
Armor Weird ness and blocks

### ISSUE THREAD

**Issue by ashly138** [SleepyTrousers/EnderZoo#81]
whene if got EnderZoo-1.7.10-1.0.11.27 installed 
http://postimg.org/image/k0rcvp7bx/

Weird Armor rendering and you can see lines on the brick stairs.

Whene i install EnderZoo-1.7.10-1.0.10.25 everything is normal.

p.s   using EnderIO-1.7.10-2.3.0.372_beta.jar too
        Forge is 10.13.3.1370
        Log http://paste.ee/p/eFAgF

**Comment by Gotolei** [comment]
I'm getting this problem as well. It seems that when items rendered a certain way, every pixel is drawn as a separate block.

Problem introduced after updating Ender Zoo from 1.0.9.18 (apparently past .25) to 1.0.11.27.
Displays fine on initial world load, but doing a search in NEI triggers it.

Before, no issue: http://i.imgur.com/E50ZCny.png
After, glitched: http://i.imgur.com/4T8gekv.png

**Comment by ate0ate** [comment]
I've been trying to track down which mod was causing this for a few days now lol. Never suspected Ender Zoo. Snow biomes were looking terrible with this bug! Thanks for the fix, much appreciated:)
