### ISSUE TITLE
Farming station just dissappearing

### ISSUE THREAD

**Issue by Mjir** [SleepyTrousers/EnderZoo#86]

**Comment by MatsJenssen** [comment]
Modpack: Skyfactory2.
When placing it down it is ok. But after a short while 10sec-20min it just dissappear. Like it's replaced with air. It's hooked up to a reactor. With ender io conduit(item and energy). Under the field it's working on there is also a layer of lilypad of fertility. Any suggestions to a fix?

**Comment by Mjir** [comment]
Problem seem to be with the layer of lilypads, When removed the farming station has been active for several hours.

**Comment by goldenapple3** [comment]
Wring mod here, buddy. The Farming Station is from [EnderIO](https://github.com/SleepyTrousers/EnderIO), not from EnderZoo.

**Comment by CrazyPants** [comment]
Could you please post this in the eio issue tracker. This is for EnderZoo
