### ISSUE TITLE
Dire Wolves still spawn in all light levels Enderzoo 1.0.11.27

### ISSUE THREAD

**Issue by Xyrys** [SleepyTrousers/EnderZoo#88]
Hi,

Updated to latest version of enderzoo (1.0.11.27) today in the hope of stopping the direwolf spawning, and the sound issues.  The sound changes are awesome btw.  

Watched them spawn after almost being killed twice.  During the day in a fully lit open area.  No Yellow or red markers as seen by F7.  They seem to be able to spawn really close as long as there is a wall inbetween..  ie: out of sight.  In both instances where I almost died I was running from where I was working in one chunk then to next chunk then back, about 20 blocks total.  High wall separating the chunks.  Dire Wolves spawned on opposite side of wall twice in a row..  ie: Killed first bunch after running through opening, then ran back through and another pack had spawned, all in the space of about 30 seconds.

I am playing the FTB Regrowth Pack standard with just the enderzoo updated today.

If this is intended, I will just leave them disabled.

Xy.

**Comment by tterrag1098** [comment]
This is intended, they spawn like vanilla wolves. However in this version they have been changed to *only spawn on grass*. They will not spawn in well lit buildings, only grass, like every other peaceful/neutral animal.
