### ISSUE TITLE
Wither Cat weird texture

### ISSUE THREAD

**Issue by jmfe10** [SleepyTrousers/EnderZoo#89]
I added the mod to my pack and for no reason the wither cat is like a simple vanilla cat with a gray box throught itself.

![2015-05-03_08 58 17](https://cloud.githubusercontent.com/assets/12219971/7444935/a897e800-f172-11e4-9181-e9ffe96e7c37.png)

**Comment by HenryLoenwind** [comment]
You got the one version that has debug frames enabled. Just grab a newer one...

**Comment by jmfe10** [comment]
Ok, thank you!!!
