### ISSUE TITLE
Ender io and Botania compatibility (dont know why it went to ender zoo :( sorry just close it here.)

### ISSUE THREAD

**Issue by Bellwar** [SleepyTrousers/EnderZoo#93]
I have problem with ender Io item conduit connecting redstring container. Im playing botania 191 build and ender io 2.2.8.381. 

Screenshots: http://imgur.com/8nVgPas,jUVpUJs#0

**Comment by MatthiasMann** [comment]
@Bellwar why are you posting that on the EnderZoo issue tracker?
