### ISSUE TITLE
Server Crash with Gas Pipe

### ISSUE THREAD

**Issue by JosephRymer** [SleepyTrousers/EnderZoo#94]
Hello im a gamer with xtremeidiots.com and your gas comduit will crash a server if you try to interface it with meknism i might suggest fixing that

**Comment by TehNut** [comment]
Last I checked, there were no Gas Conduits in Ender Zoo.

**Comment by tterrag1098** [comment]
Don't bother, this issue was fixed almost a month ago. Please update EnderIO.
