### ISSUE TITLE
Computercraft support for Capacitor bank

### ISSUE THREAD

**Issue by soulji** [SleepyTrousers/EnderZoo#97]
For what I can tell, the 2 useful methods/functions for computer craft is getMaxEnergyStored and getEnergyStored.  I was wondering if you could add a couple more such as:

setMaxInput - modify the maximum amount of energy the capacitor bank will take in
setMaxOutput - modify the maximum amount of energy the capacitor bank will give
getMaxIO - get max allowable input/output the capacitor can produce
getCurrentUsage - get current input/output of rf/t (not as needed)

story as to why (no need to read the rest..)
Being able to do this will help with minimizing the power usage of my big reactor, which can produce 500k, but I only want it to produce the minimum amount necessary to keep my capacitor bank full.

**Comment by AnrDaemon** [comment]
EnderZoo? Seriously?

**Comment by soulji** [comment]
well I didn't even realize... I'll try moving it
