### ISSUE TITLE
[Suggestion] Config: Powered lights RF/tick cost

### ISSUE THREAD

**Issue by arkcane** [SleepyTrousers/EnderZoo#98]
I find that Powered lights use up to much RF a Tick for anyone on my survival server to actually use. but I understand that for the sake of over all balance why it is as high as it is.

Could we get the cost per tick as part of the config so that I can tune it.

Thank you for your consideration

**Comment by MatthiasMann** [comment]
EnderZoo has no powered lights!

**Comment by arkcane** [comment]
Sorry wrong github
